export default {
  SET_LAST_ID: 'SET_LAST_ID',
  TEST_REQUEST_START_FETCHING: 'TEST_REQUEST_START_FETCHING',
  TEST_REQUEST_STOP_FETCHING: 'TEST_REQUEST_STOP_FETCHING',
  TEST_REQUEST_ERROR_FETCHING: 'TEST_REQUEST_ERROR_FETCHING'
};
